config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
 # post 'users', to: 'users#create'
  # Defines the root path route ("/")
  # root "articles#index"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:6, maximum:100}
  validates :description, presence: true, length: {minimum:10, maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy] #where is method used

  def show
  end

  def index

    @articles = Article.paginate(page: params[:page], per_page: 3)



  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params) #simply call method from private
    @article.user = current_user
    if @article.save
      redirect_to @article
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private #without end block (should always be to the bottom)

  #method for getting and ID
  def set_article
  @article = Article.find(params[:id])
  end

  #method for params
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

    redirect_to articles_path if logged_in?

  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
          redirect_to login_path
          flash[:notice] = "Wrong login credentials!"


        end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path

  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
   # @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page:3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def edit
  #  @user = User.find(params[:id])
  end

  def update
  #  @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Successfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.present?
      @user.destroy
    end
    redirect_to users_path
  end

  def set_user
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end

  # def logged_in?
  #   !!current_user
  # end

end

app/views/articles/_article.html.erb
<table border="2px";>
    <thead>
        <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Desc</th>
            <th>Created</th>
            <th>Updated</th>
            <th colspan="3">Action</th>
         
            </tr>
        </thead>

    <tbody>

        <% @articles.each do |article| %>
        <tr>
            <% if article.user %>
            <td>Articles by <%= link_to article.user.username, user_path(article.user) %></td>
            <% end %>
            <td><%= article.title %></td>
            <td><%= article.description %></td>

    <td><small><%= time_ago_in_words(article.created_at)%> ago</small></td>
        <td><small><%= time_ago_in_words(article.updated_at)%> ago</small></td>
        


             <td><%= link_to 'Show', article_path(article) %></td>
         <% if logged_in? && article.user == current_user %>
         
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article.id), data: { turbo_method: :delete , turbo_confirm: "Are you sure?" }
        %>
     
        </td>    <% end %>

               </tr>
              <% end %>
        </tbody>
    </table> 

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<%= render 'layouts/navigation' %>

<h1>Edit article</h1> 

<%= render 'form'%>


<%= link_to 'Cancel', articles_path(@article) %>

app/views/articles/index.html.erb
<%= render 'layouts/navigation' %>

<br>All articles
<p><div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div></p>
<%= render 'article' %>
         <% if logged_in? %>

<p>
    <%= link_to 'Create new article', new_article_path %></p>
    <BR> <% end %>
    <p> 
        <div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>
        </p>

<p>


</p>

app/views/articles/new.html.erb
<%= render 'layouts/navigation' %>

Create a new article

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path(@article) %>

app/views/articles/show.html.erb
<%= render 'layouts/navigation' %>
<H1>Details</h1>


<p>Title: <%= @article.title %>  </p>
<p>Description: <%= @article.description %>  </p>
<p>by <%= @article.user.username if @article.user %></p>
<% if logged_in? && @user == current_user %>
<%= link_to 'Edit', edit_article_path(@article) %>|
<%= link_to 'Delete', article_path(@article), data:{ turbo_method: :delete , turbo_confirm: "Are you sure?" } %> 
<% end %>
<p> <%= link_to 'Return to all articles listing', articles_path(@article) %> <br>
<%= link_to 'Return to this users articles', user_path(@article.user) %>
</p>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %> 
  <%= msg %> 
<% end %>

app/views/layouts/_navigation.html.erb
<nav >
  <%= link_to "ALPHA BLOG", root_path %>
  
  <div  >
    <ul >
      <li >
        <%= link_to "Users", users_path %>
      </li>
      <li >
        <div >
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path %>
          <% end %>  
          <%= link_to "View articles", articles_path %>
         
     
    
      <% if logged_in? %>
        <li >

          <div >
            <%= link_to "View your profile", user_path(current_user) %>
            <%= link_to "Edit your profile", edit_user_path(current_user) %>
            <%= link_to "Delete profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <li >
          <%= link_to 'Logout', logout_path,  method: :delete %>
        </li>
      <% else %>
        <li >
          <%= link_to 'Log in', login_path %>
        </li>
        <li >
          <%= link_to 'Sign up', signup_path %>
        </li>
      <% end %>
      </ul>
    <form >
      <input  type="search" placeholder="Search" aria-label="Search">
      <button  type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render 'layouts/messages' %> <!-- no need for _ sign -->
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'layouts/navigation' %>

About page 
<%=link_to 'Articles listing', articles_path%> |
<%=link_to 'Home', root_path%> <!-- Homepage is root path -->

app/views/pages/home.html.erb
Index page <br>
<%= render 'layouts/navigation' %>
<!--<p>

        <%= link_to 'Log in', login_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', logout_path, method: :delete %>
    </p>-->


<!--
<p>
<%=link_to 'Articles listing', articles_path%> <br>
<%=link_to 'About page', about_path%><br>
<%= link_to 'Sign up!', signup_path %><br>
<%= link_to 'List of users', users_path%><br>
<% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username.capitalize, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
</p> >

app/views/users/_form.html.erb
  <h2>The following errors prevented the article from being saved</h2>
 
<%= form_with(model: @user, local: true) do |f| %>

  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </p>

 <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>

  <p>
    
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/navigation' %>

<h1> Edit your profile </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'layouts/navigation' %>
<h1> List of users </h1><br>
<p>
<div class="flickr_pagination">
<%= will_paginate @users, :container => false %>
  </div></p>

<table border="2px";>
    <thead>
        <tr>
            <th>Username</th>
            <th>E mail</th>
            <th>No of articles</th>
                <th>Joined</th>
            <th colspan="3">Action</th>
                    

            </tr>
        </thead>

    <tbody>

        <% @users.each do |user| %>
        <tr>
            <td><%= link_to user.username, user %></td>
            <td><%= user.email %></td>
            <td><%= pluralize(user.articles.count, "article") %></td>
          <td><small><%= time_ago_in_words(user.created_at)%> ago</small></td>
             <td><%= link_to 'Show', user %></td>

<% if logged_in? && @user == current_user %>
        
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user_path(user.id), data: { turbo_method: :delete , turbo_confirm: "Are you sure?" }
        %></td>  <% end %>    
          </tr>

              <% end %>
        </tbody> 
    </table>
    <p>
    <div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>
 </p>

app/views/users/new.html.erb
<%= render 'layouts/navigation' %>
<h1> Sign up </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'layouts/navigation' %>
<h1> <%= @user.username%>'s profile </h1>
<ul>
<% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'Home', root_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path,  method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path %>
        </li>
<!--        <li class="nav-item">
          <%= link_to 'Sign up', signup_path %>
        </li>-->
      <% end %>
      </ul>
           <% if logged_in? && @user == current_user %>
<p>
<%= link_to "Edit your profile", edit_user_path(@user)%>
</p><% end %>
<p>
<div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>
</p>
<%= render 'articles/article' %>
<p>
<%= link_to 'Return to articles listing', articles_path(@article) %><br>

             <% if logged_in? && @user == current_user %>
 
    <%= link_to 'Create new article', new_article_path %></p><% end %>

</p>
<p>
    
<div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>
    </p>